version: "3.8"

networks:
  meetup_network:

services:
  app_dev:
    networks:
      - meetup_network
    container_name: meetup_api_dev
    build:
      context: .
      target: DEV
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
  db:
    networks:
      - meetup_network
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

